-- MySQL Script generated by MySQL Workbench
-- Fri Jun 19 21:29:08 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `profile_image` BLOB NULL,
  `account_creation` DATETIME NOT NULL,
  `country` VARCHAR(255) NULL,
  `gender` VARCHAR(45) NULL,
  `birthday` DATE NULL,
  `age` INT NULL,
  PRIMARY KEY (`idUsers`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `idUsers_UNIQUE` (`idUsers` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recipes` (
  `idRecipes` INT NOT NULL AUTO_INCREMENT,
  `Users_idUsers` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `instructions` MEDIUMTEXT NOT NULL,
  `prep_time` INT NOT NULL,
  `cooking_time` INT NOT NULL,
  `num_servings` INT NOT NULL,
  `images` BLOB NULL,
  `date_posted` DATETIME NOT NULL,
  PRIMARY KEY (`idRecipes`, `Users_idUsers`),
  INDEX `fk_Recipes_Users1_idx` (`Users_idUsers` ASC) VISIBLE,
  UNIQUE INDEX `idRecipes_UNIQUE` (`idRecipes` ASC) VISIBLE,
  CONSTRAINT `fk_Recipes_Users1`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comments` (
  `idComments` INT NOT NULL AUTO_INCREMENT,
  `Recipes_idRecipes` INT NOT NULL,
  `Users_idUsers` INT NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `date_posted` DATETIME NOT NULL,
  PRIMARY KEY (`idComments`, `Recipes_idRecipes`, `Users_idUsers`),
  INDEX `fk_Comments_Recipes1_idx` (`Recipes_idRecipes` ASC) VISIBLE,
  INDEX `fk_Comments_Users1_idx` (`Users_idUsers` ASC) VISIBLE,
  UNIQUE INDEX `idComments_UNIQUE` (`idComments` ASC) VISIBLE,
  CONSTRAINT `fk_Comments_Recipes1`
    FOREIGN KEY (`Recipes_idRecipes`)
    REFERENCES `mydb`.`Recipes` (`idRecipes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comments_Users1`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ratings` (
  `idRatings` INT NOT NULL AUTO_INCREMENT,
  `Recipes_idRecipes` INT NOT NULL,
  `Users_idUsers` INT NOT NULL,
  `num_stars` INT NOT NULL,
  `date_posted` DATETIME NOT NULL,
  PRIMARY KEY (`idRatings`, `Recipes_idRecipes`, `Users_idUsers`),
  INDEX `fk_Ratings_Recipes1_idx` (`Recipes_idRecipes` ASC) VISIBLE,
  INDEX `fk_Ratings_Users1_idx` (`Users_idUsers` ASC) VISIBLE,
  UNIQUE INDEX `idRatings_UNIQUE` (`idRatings` ASC) VISIBLE,
  CONSTRAINT `fk_Ratings_Recipes1`
    FOREIGN KEY (`Recipes_idRecipes`)
    REFERENCES `mydb`.`Recipes` (`idRecipes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ratings_Users1`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ingredients` (
  `idIngredients` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` MEDIUMTEXT NULL,
  PRIMARY KEY (`idIngredients`),
  UNIQUE INDEX `idIngredients_UNIQUE` (`idIngredients` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Saved_Recipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Saved_Recipes` (
  `idSaved_Recipes` INT NOT NULL,
  `Users_idUsers` INT NOT NULL,
  PRIMARY KEY (`idSaved_Recipes`, `Users_idUsers`),
  INDEX `fk_Saved_Recipes_Users1_idx` (`Users_idUsers` ASC) VISIBLE,
  CONSTRAINT `fk_Saved_Recipes_Users1`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Followers_has_Followers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Followers_has_Followers` (
  `Followers_idFollowers` INT NOT NULL,
  PRIMARY KEY (`Followers_idFollowers`),
  INDEX `fk_Followers_has_Followers_Followers_idx` (`Followers_idFollowers` ASC) VISIBLE,
  CONSTRAINT `fk_Followers_has_Followers_Followers`
    FOREIGN KEY (`Followers_idFollowers`)
    REFERENCES `mydb`.`Followers` (`idFollowers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users_has_Followers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users_has_Followers` (
  `Users_idUsers` INT NOT NULL,
  `Followers_idFollowers` INT NOT NULL,
  PRIMARY KEY (`Users_idUsers`, `Followers_idFollowers`),
  INDEX `fk_Users_has_Followers_Followers1_idx` (`Followers_idFollowers` ASC) VISIBLE,
  INDEX `fk_Users_has_Followers_Users1_idx` (`Users_idUsers` ASC) VISIBLE,
  CONSTRAINT `fk_Users_has_Followers_Users1`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Followers_Followers1`
    FOREIGN KEY (`Followers_idFollowers`)
    REFERENCES `mydb`.`Followers` (`idFollowers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ingredients_has_Recipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ingredients_has_Recipes` (
  `Ingredients_idIngredients` INT NOT NULL,
  `Recipes_idRecipes` INT NOT NULL,
  `Recipes_Users_idUsers` INT NOT NULL,
  PRIMARY KEY (`Ingredients_idIngredients`, `Recipes_idRecipes`, `Recipes_Users_idUsers`),
  INDEX `fk_Ingredients_has_Recipes_Recipes1_idx` (`Recipes_idRecipes` ASC, `Recipes_Users_idUsers` ASC) VISIBLE,
  INDEX `fk_Ingredients_has_Recipes_Ingredients1_idx` (`Ingredients_idIngredients` ASC) VISIBLE,
  CONSTRAINT `fk_Ingredients_has_Recipes_Ingredients1`
    FOREIGN KEY (`Ingredients_idIngredients`)
    REFERENCES `mydb`.`Ingredients` (`idIngredients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingredients_has_Recipes_Recipes1`
    FOREIGN KEY (`Recipes_idRecipes`)
    REFERENCES `mydb`.`Recipes` (`idRecipes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recipes_has_Ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recipes_has_Ingredients` (
  `Recipes_idRecipes` INT NOT NULL,
  `Ingredients_idIngredients` INT NOT NULL,
  `quantity` INT NOT NULL,
  `weight` VARCHAR(45) NOT NULL,
  `other_desc` VARCHAR(255) NULL,
  PRIMARY KEY (`Recipes_idRecipes`, `Ingredients_idIngredients`),
  INDEX `fk_Recipes_has_Ingredients_Ingredients1_idx` (`Ingredients_idIngredients` ASC) VISIBLE,
  INDEX `fk_Recipes_has_Ingredients_Recipes1_idx` (`Recipes_idRecipes` ASC) VISIBLE,
  CONSTRAINT `fk_Recipes_has_Ingredients_Recipes1`
    FOREIGN KEY (`Recipes_idRecipes`)
    REFERENCES `mydb`.`Recipes` (`idRecipes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recipes_has_Ingredients_Ingredients1`
    FOREIGN KEY (`Ingredients_idIngredients`)
    REFERENCES `mydb`.`Ingredients` (`idIngredients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Saved Recipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Saved Recipes` (
  `Users_idUsers` INT NOT NULL,
  `Recipes_idRecipes` INT NOT NULL,
  `bookmarked_date` DATETIME NOT NULL,
  PRIMARY KEY (`Users_idUsers`, `Recipes_idRecipes`),
  INDEX `fk_Users_has_Recipes_Recipes1_idx` (`Recipes_idRecipes` ASC) VISIBLE,
  INDEX `fk_Users_has_Recipes_Users1_idx` (`Users_idUsers` ASC) VISIBLE,
  CONSTRAINT `fk_Users_has_Recipes_Users1`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Recipes_Recipes1`
    FOREIGN KEY (`Recipes_idRecipes`)
    REFERENCES `mydb`.`Recipes` (`idRecipes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users_has_Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users_has_Users` (
  `Users_idUsers` INT NOT NULL,
  `Users_idUsers1` INT NOT NULL,
  PRIMARY KEY (`Users_idUsers`, `Users_idUsers1`),
  INDEX `fk_Users_has_Users_Users2_idx` (`Users_idUsers1` ASC) VISIBLE,
  INDEX `fk_Users_has_Users_Users1_idx` (`Users_idUsers` ASC) VISIBLE,
  CONSTRAINT `fk_Users_has_Users_Users1`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Users_Users2`
    FOREIGN KEY (`Users_idUsers1`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Followers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Followers` (
  `idFollower` INT NOT NULL,
  `idFollowed` INT NOT NULL,
  `followed_date` DATETIME NOT NULL,
  PRIMARY KEY (`idFollower`, `idFollowed`),
  INDEX `fk_Users_has_Users1_Users2_idx` (`idFollowed` ASC) VISIBLE,
  INDEX `fk_Users_has_Users1_Users1_idx` (`idFollower` ASC) VISIBLE,
  CONSTRAINT `fk_Users_has_Users1_Users1`
    FOREIGN KEY (`idFollower`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Users1_Users2`
    FOREIGN KEY (`idFollowed`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
